### ISSUE TITLE
typos in the docs: openmv 1.4.4

### ISSUE THREAD

**Issue by wminarik** [openmv/openmv-doc#1]
https://openmv.io/docs/openmvcam/hardware/index.html

The thermal sensor on the thermopile shield: Melexis MLX90620

--> should this be Melexis **MLX90621** ?

https://openmv.io/docs/library/omv.sensor.html

sensor.get_id()

--> returns 119 instead of OV7725

https://openmv.io/docs/library/omv.gif.html

Use ~~gif~~ for long clips.

---> should be: Use **mjpeg** for long clips.

https://openmv.io/docs/library/omv.fir.html

second instance of draw_ta(image, ir, alpha=128, scale=[auto, auto]):

should be: **draw_ir(**

**Comment by kwagyeman** [comment]
Thanks, I'll get to this when I update the docs. Right now I'm working on the IDE. We'll have a boot loader feature coming out soon along with an auto-update feature to let you know when I release new software. Finally, I got a cert for windows so the IDE will be digitally signed and hopefully the driver too.

**Comment by kwagyeman** [comment]
Fixed.
