### ISSUE TITLE
Histogram object has no method get_threshold nor get_threhsold

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv-doc#2]
[The documentation for the Histogram object](http://docs.openmv.io/library/omv.image.html?highlight=image#class-histogram-histogram-object) mentions a method called "[get_threhsold](http://docs.openmv.io/library/omv.image.html?highlight=image#image.histogram.get_threhsold)". I tried that and it doesn't work. More surprisingly was that fact that "get_threshold" also didn't work.

```
Traceback (most recent call last):
  File "<stdin>", line 37, in <module>
AttributeError: 'histogram' object has no attribute 'get_threhsold'
MicroPython v1.9.2-4442-g8d787e97 on 2018-01-24; OPENMV3 with STM32F765
Type "help()" for more information.
>>> 

Traceback (most recent call last):
  File "<stdin>", line 37, in <module>
AttributeError: 'histogram' object has no attribute 'get_threshold'
MicroPython v1.9.2-4442-g8d787e97 on 2018-01-24; OPENMV3 with STM32F765
Type "help()" for more information.
```

**Comment by kwagyeman** [comment]
Yes, this looks to be an error where the method somehow didn't make it into the firmware. It will be in the next release which we plan to get out by next week.

**Comment by kwagyeman** [comment]
Fixed for the next release.
