### ISSUE TITLE
Threshold spelled "Threhsold"

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv-doc#3]
Maybe this is on purpose, but [the documentation](http://docs.openmv.io/library/omv.image.html?highlight=image#class-threhsold-threshold-object) misspells "threshold" as "threhsold".

**Comment by kwagyeman** [comment]
That's a bug. Will fix. Thanks!

**Comment by kwagyeman** [comment]
Fixed for the next release coming next week.
