### ISSUE TITLE
Update winc.ifconfig

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv-doc#6]
http://docs.openmv.io/library/network.html?highlight=ifconfig#network.winc.ifconfig

It's now exactly like the "standard" network.ifconfig. 

http://docs.openmv.io/library/network.html?highlight=ifconfig#network.ifconfig

Without args it returns (ip, subnet, gateway, dns). Called with (ip, subnet, gateway, dns) it sets a static IP.

Please add a note to set a static IP, ifconfig() it should be called before connect(). For example:

```
wlan = network.WINC()
wlan.ifconfig(('192.168.1.100', '255.255.255.0', '192.168.1.1', '192.168.1.1'))
wlan.connect(SSID, key=KEY, security=wlan.WPA_PSK)
```

Otherwise DHCP is used by default.

**Comment by kwagyeman** [comment]
Done
